### ISSUE TITLE
use strapi-provider-upload-m3-minio for upload plugin

### ISSUE THREAD

**Issue by Nilegfx** [m3ntorship/m3ntorship.com#29]
follow the same as what we did in charity project. 

https://github.com/m3ntorship/charity-cms/blob/b36e0ca0b4099d1cf4acb653ec09fbc6e9d88234/package.json#L31

use `m3ntorshipcom` as a bucket name with the same credentials as in charity

**Comment by elhaw** [comment]
the configuration has been done.
