### ISSUE TITLE
(Effect) Performance Optimization

### ISSUE THREAD

**Issue by elhaw** [m3ntorship/m3ntorship.com#347]

**Comment by AbudZohair** [comment]
**Instructuions**

- Audit Every single page  and pay more attention to the Home page
- Use Lighthouse CLI or lighthouse in browser if you don't have scripts or extensions that may affect the Audit result.
### Opportunities:

**1.  In head tag (_document) file**

**- Preconnect to required origins**
> https://www.googletagmanager.com  &&  https://www.google-analytics.com && We could add our image server also https://s3.m3ntorship.net
> **check**: [preconnect-and-dns-prefetch](https://web.dev/preconnect-and-dns-prefetch/)

**- Extract Critical CSS for the above fold**
> **check** https://web.dev/extract-critical-css/  and you could extract it manually via: [crtical css extractor](https://www.sitelocity.com/critical-path-css-generator) [Link 2](https://pegasaas.com/critical-path-css-generator/)

**2. Images**

- Defer offscreen images (lazyload Images)
- Optimize all svg images manually via [svgomg](https://jakearchibald.github.io/svgomg/) or any other website then reupload it to strapi 

**3. General**

- add font-display (swap or fallback) to @font-face and move the fonts folder the public folder
- check cumulative layout shifts for the header section 
- check Animation Behavior and try to enhance it

**4. Nice to be Checked**
- HTTP/2 on server
- time to interactive
- Minimize main-thread work
- introduce lighthouse CLI to GitHub actions 

Resources: 

- https://web.dev/optimize-lcp/
- https://web.dev/vitals/
-

**Comment by Nilegfx** [comment]
very good analysis and outcome, @AbudZohair!

Hihgly appreciate your effort and time to collect, share, and write it down in a professional manner.
